kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: exodus
  name: exodus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: exodus
  template:
    metadata:
      labels:
        k8s-app: exodus
    spec:
      containers:
        - name: exodus
          image: "gcr.io/xxcloud/exodus:7e24080"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: INFLUX_HOST
              valueFrom:
                secretKeyRef:
                  name: influx
                  key: INFLUX_HOST
            - name: INFLUX_PORT
              valueFrom:
                secretKeyRef:
                  name: influx
                  key: INFLUX_PORT
            - name: INFLUX_PASS
              valueFrom:
                secretKeyRef:
                  name: influx
                  key: INFLUX_PASS
            - name: INFLUX_USER
              valueFrom:
                secretKeyRef:
                  name: influx
                  key: INFLUX_USER
          resources:
            limits:
              cpu: "1"
              memory: 912Mi
            requests:
              cpu: 100m
              memory: 312Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gcr-json-key
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: exodus
  name: exodus
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: exodus
