kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: exodus
  name: exodus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: exodus
  template:
    metadata:
      labels:
        k8s-app: exodus
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: exodus
          image: gcr.io/xxcloud/exodus:c57d1e6
          resources:
            requests:
              cpu: 0.1
              memory: 312Mi
            limits:
              cpu: 1
              memory: 912Mi
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: SAVE_PREDICTION
              value: "true"
            - name: FINNHUB_KEY
              valueFrom:
                secretKeyRef:
                  name: finnhub
                  key: FINNHUB_KEY
            - name: RETHINKDB_HOST
              valueFrom:
                secretKeyRef:
                  name: rethinkdb
                  key: host
            - name: RETHINKDB_PORT
              valueFrom:
                secretKeyRef:
                  name: rethinkdb
                  key: port
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: exodus
  name: exodus
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: exodus
