kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: fluxer
  name: fluxer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fluxer
  template:
    metadata:
      labels:
        k8s-app: fluxer
    spec:
      containers:
        - name: fluxer
          image: "gcr.io/xxcloud/fluxer:7e24080"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: INFLUX_URL
              valueFrom:
                secretKeyRef:
                  name: fluxer
                  key: INFLUX_URL
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fluxer
                  key: INFLUX_TOKEN
            - name: INFLUX_ORG
              valueFrom:
                secretKeyRef:
                  name: fluxer
                  key: INFLUX_ORG
            - name: INFLUX_BUCKET
              valueFrom:
                secretKeyRef:
                  name: fluxer
                  key: INFLUX_BUCKET
          resources:
            limits:
              cpu: "1"
              memory: 912Mi
            requests:
              cpu: 100m
              memory: 312Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: gcr-json-key
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: fluxer
  name: fluxer
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: fluxer
