version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  k8s: digitalocean/k8s@0.1.1

jobs:
  build:
    machine: true
    steps:
      - checkout

      - gcp-gcr/gcr-auth

      - gcp-gcr/build-image:
          registry-url: gcr.io
          image: exodus
          tag: ${CIRCLE_SHA1:0:7}

      - gcp-gcr/push-image:
          registry-url: gcr.io
          image: exodus
          tag: ${CIRCLE_SHA1:0:7}

      - k8s/install

      - k8s/initialize:
          cluster: cloudx

      - run:
          name: Update Exodus Server Deployment
          command: kubectl set image deployment/exodus exodus=gcr.io/xxcloud/exodus:${CIRCLE_SHA1:0:7}

workflows:
  version: 2
  exodus-pipeline:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
