name: "publish"

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: "publish"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      # Setup Node.js
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12

      # Automated Version Bump
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Install packages
      - name: "Install"
        run: npm install

      # Build packages
      - name: "Install"
        run: npm run build

      # Publish the the main package
      - name: npm publish main
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish --access=public
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
